---
development:
  cloud_name: duovuuybb
  api_key: '151152912567472'
  api_secret: Sy-ihQf3_UoHwkOdIeTC6Y_LId0
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: duovuuybb
  api_key: '151152912567472'
  api_secret: Sy-ihQf3_UoHwkOdIeTC6Y_LId0
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: duovuuybb
  api_key: '151152912567472'
  api_secret: Sy-ihQf3_UoHwkOdIeTC6Y_LId0
  enhance_image_tag: true
  static_image_support: false
